### ISSUE TITLE
netstandard port please!!!

### ISSUE THREAD

**Issue by eaba** [kevbite/MassTransit.MessageData.Enchilada#3]

**Comment by kevbite** [comment]
This shouldn't be too hard... I'll take a look in the new few days. (unless you manage it before me ;-) )

**Comment by kevbite** [comment]
THIS SHOULD BE UPDATED TO DOTNET STANDARD NOW!!! 👍 

https://www.nuget.org/packages/MassTransit.MessageData.Enchilada/2.0.0

**Comment by eaba** [comment]
@kevbite thanks.......I actually copied the codes into a new netstandard library class. Going forward, I would prefer your new package

**Comment by kevbite** [comment]
Should have just forked the project and sent a PR 👍  anyway it supports netstandard now
